version: '3'
services:
  mariadb:
    build: ./mariadb/.
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: AppleSucks
    ports:
      - "49160:3306"
    volumes:
      - ./mariadb/dbs:/var/lib/mysql
    links:
      - php
      - nginx
  nginx:
    build: ./nginx/.
    ports:
      - "8888:80"
    volumes:
      - ./data:/code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./php/.
    environment:
      FILE_UPLOADS : "On"
      ALLOW_URL_FOPEN : "On"
      MEMORY_LIMIT : 256
      UPLOAD_MAX_FILESIZE : "100M"
      MAX_EXECUTION_TIME : 360
    ports:
      - "9000:9000"
    # seems like fpm receives the full path from nginx
    # and tries to find the files in this dock, so it must
    # be the same as nginx.root
    volumes:
        - ./data:/code



